logging:
  level.com.hussein: debug
  level.org.springframework.jdbc.core.JdbcTemplate: debug
  pattern:
    console: "%d{yyyy/MM/dd-HH:mm:ss} [%thread] %-5level %logger- %msg%n"
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot?useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
