logging:
  level.com.hussein: debug
  pattern:
    console: "%d{yyyy/MM/dd-HH:mm:ss} [%thread] %-5level %logger- %msg%n"
spring:
  servlet:
    multipart:
      max-file-size: 128KB
      max-request-size: 128KB